"""initial schema

Revision ID: bccc81fcad8e
Revises: 
Create Date: 2025-07-29 00:52:03.747963

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bccc81fcad8e'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_credentials',
    sa.Column('user_email', sa.String(), nullable=False),
    sa.Column('token_json', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('user_email')
    )
    op.create_index(op.f('ix_user_credentials_user_email'), 'user_credentials', ['user_email'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_credentials_user_email'), table_name='user_credentials')
    op.drop_table('user_credentials')
    # ### end Alembic commands ###
